%BifurDiag.m is a Matlab program to construct a bifurcation diagram for the logistic map
%to allow exploring the period doubling route to Chaos.  Dana Kester, Oct. 2002

%  The logistic map is x[t+1] = r*x[t]*(1-x[t]) where 0 < r < 4 is a parameter
%  value and 0 < x[t] < 1 is a variable.  The user specifies the following:
%  rmin = the lowest value of r to three decimals (or maybe two decimals)
%  rmax = the highest value of r to three decimals (or maybe two decimals)
%  xo = initial value of x[t]
%  num = number of iterations

%  WARNING THE CURRENT PARAMETERS rmin, rmax, and num, (as well as the derived rmn, rmx)
%  MAY RESULT IN A LONG EXECUTION TIME -- ON MY 4-YEAR OLD COMPUTER WITH A PENTIUM II
%  166 MHZ PROCESSOR IT TOOK ABOUT 7 HOURS!  YOU CAN REDUCE THE NUMBER OF CALCULATIONS
%  BY INCREMENTING R-VALUES BY 0.01 RATHER THAN 0.001 BY CHANGING rmin and rmax TO TWO
%  DECIMAL PLACES AND CHANGING 1000 TO 100 IN LINES 24 & 25; OR YOU CAN NARROW THE 
%  RANGE OF R-VALUES; OR YOU MAY BE ABLE TO REDUCE THE NUMBER OF ITERATIONS AT EACH 
%  R-VALUE.  IT ALL DEPENDS ON WHAT YOU WANT TO EXAMINE IN THE BIFURCATION DIAGRAM.

clear
rmin = 2.001
rmax = 3.999
xo = 0.6
num = 400
num2 = num/2;

rmn = round(rmin*1000); %Matlab requires integer subscripts
rmx = round(rmax*1000);
rct = 0; %rct is a counter for the number of r-values interated
ir = 0;
for r = rmin:0.001:rmax
    x(1)=xo; %set initial condition--Matlab requires subscript > 0
        rdec = r; % converts back to decimal r
    for n=2:num
        x(n)=rdec*(x(n-1))*(1-(x(n-1)));
        if n > num2
            ir = ir+1;%n+(num-2)*rct; %ir is a counter for total interations
            itx(ir) = x(n); %after the first num2 iterations
            rv(ir)=rdec;
        end
    end
    rct=rct+1;
end


plot(rv,itx,'.')
axis([floor(rmin),ceil(rmax),0,1])
numitr = num2str(num);
title(['Bifurcation Diagram for the Logistic Map with Interations = ',numitr])

%  Note: The plot generated by this program needs some interactive editing in the Matlab GUI.
%  The default point size is "6", and I have not found a way to change that in the program.
%  If you enter PLOT EDIT mode you can select the data plotted and change the point size from
%  6 to 0.5 to show the detail of the results.