% draw the plot using x_vals, y_vals and t
%fixed foint
t = 100;
x=0.5;
y=1.0;
rho=0.1394;
gamma = 0.1735;
[x_vals, y_vals] = drawxyplot(x,y,t,rho,gamma);
x_axis = 0:1:t;
y_axis = x_vals;
yyaxis left;
subplot(3,1,1), plot(x_axis,y_axis);
title('Fixed Point');
ylabel('X values');
xlabel('t values');
yyaxis right;
y_axis = y_vals;
subplot(3,1,1),plot(x_axis,y_axis,'--');
ylabel('Y values');

hold on;
%rho=0.1;
%gamma = 0.7796;
rho = 1.0455;
gamma = 0.2469;
[x_vals, y_vals] = drawxyplot(x,y,t,rho,gamma);
x_axis = 0:1:t;
y_axis = x_vals;
yyaxis left;
subplot(3,1,2), plot(x_axis,y_axis);
title('Limit Cycle');
ylabel('X values');
xlabel('t values');
yyaxis right;
y_axis = y_vals;
subplot(3,1,2),plot(x_axis,y_axis,'--');
ylabel('Y values');

hold on;
t=9100;
rho=1.1242;
gamma = 0.4673;
[x_vals, y_vals] = drawxyplot(x,y,t,rho,gamma);
x_axis = 9001:1:t;
y_axis = x_vals(9001:t);
yyaxis left;
subplot(3,1,3), plot(x_axis,y_axis);
title('Complex');
ylabel('X values');
xlabel('t values');
yyaxis right;
y_axis = y_vals(9001:t);
subplot(3,1,3),plot(x_axis,y_axis,'--');
ylabel('Y values');
